{ config, ... }:
{
  # Native Guacamole Server (guacd C backend)
  services.guacamole-server = {
    enable = true;
    host = "127.0.0.1";
    port = 4822;
  };

  # Native Guacamole Client (Tomcat web interface)
  services.guacamole-client = {
    enable = true;
    enableWebserver = true; # Automatically provisions Apache Tomcat

    settings = {
      guacd-hostname = "127.0.0.1";
      guacd-port = 4822;
    };

    # Point to the runtime XML template generated by sops-nix
    userMappingXml = config.sops.templates."guacamole-user-mapping.xml".path;
  };

  # serve Guacamole at / using tls
  services.caddy = {
    enable = true;

    globalConfig = ''
      default_sni guac.local
    '';

    virtualHosts = {
      # HTTPS endpoint
      "guac.local, :443" = {
        extraConfig = ''
          tls internal
          redir / /guacamole/ 302
          reverse_proxy 127.0.0.1:8080 {
            header_up Host {host}
            header_up X-Real-IP {remote_host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto https
          }
        '';
      };
      # HTTP -> HTTPS redirect
      "http://localhost:80" = {
        extraConfig = ''
          redir https://{host}{uri} permanent
        '';
      };
    };
  };
}
